easy_admin:
  entities:
    Whois:
      class: App\Entity\Whois
      list:
        title: 'Whois информация о доменах'
        actions:
          - { name: 'show', label: 'Просмотреть', icon: 'eye' }
        fields:
          - 'id'
          - { property: 'domain', label: 'Имя домена', type: 'url' }
          - 'updatedAt'